### ISSUE TITLE
Setup 3D model does not render: TypeError: Frustum.setFromMatrix is not a function

### ISSUE THREAD

**Issue by sergey-navrotskiy** [betaflight/betaflight-configurator#5546]
### Describe the bug

After updating the Betaflight App web version, the 3D aircraft model on the **Setup** tab is no longer rendered.

The attitude values (Yaw / Pitch / Roll) are updated correctly, but the 3D model area remains empty.

The browser console reports:

```text
Error loading model: TypeError: ee.setFromMatrix is not a function
    at Bd.projectScene (window_watchers-C_jDw5gp.js:4104:102875)
    at Vd.render (window_watchers-C_jDw5gp.js:4104:111306)
    at Wd.performRender (window_watchers-C_jDw5gp.js:4104:124389)
    at Wd.render (window_watchers-C_jDw5gp.js:4104:123958)
    at Wd.<anonymous> (window_watchers-C_jDw5gp.js:4104:121971)
    at window_watchers-C_jDw5gp.js:4104:122115
    at window_watchers-C_jDw5gp.js:4104:57411
    at window_watchers-C_jDw5gp.js:4104:79815

THREE.Object3D.add: object not an instance of THREE.Object3D. null
```

The problem started after updating the web version of Betaflight App.

The standalone Betaflight Configurator **10.10.0** renders the same FC/model correctly.

The web version also rendered the model correctly before the recent update.

### To Reproduce

1. Open `app.betaflight.com`.
2. Connect a flight controller.
3. Open the **Setup** tab.
4. Observe that Yaw / Pitch / Roll values are updated correctly.
5. The 3D aircraft model is not displayed.
6. Open Chrome DevTools → Console.
7. Observe:

```text
TypeError: ee.setFromMatrix is not a function
```

I also tested the option:

**Options → Enable legacy rendering for 3D model (for low performance devices)**

The model does not render with this option either enabled or disabled.

### Expected behavior

The aircraft 3D model should be displayed on the Setup tab and should follow the FC attitude, as it does in Betaflight Configurator 10.10.0.

### App version

Betaflight App: 2026.6.2 (091127c)

### Flight controller configuration

```txt

```

### Environment

```text
OS: macOS Ventura 13.7.8 (22H730)
Browser: Google Chrome 153.0.8010.53 (x86_64)
```
### Flight controller

```text
Target: KRMA/KARMAF435V1G (AT32F435G)
Firmware: Betaflight 4.5.3
```

The same flight controller works correctly with Betaflight Configurator 10.10.0.

### Additional context / possible cause

The stack trace appears to point to the legacy `CanvasRenderer` / `Projector` code.

In `src/js/utils/three/Projector.js`, the current code still contains:

```js
_frustum.setFromMatrix(_viewProjectionMatrix);
```

However, Three.js renamed:

```text
Frustum.setFromMatrix()
```

to:

```text
Frustum.setFromProjectionMatrix()
```

in r113.

This therefore looks potentially related to the old `Projector.js` / `CanvasRenderer.js` compatibility code.

This also seems related to #5379, which mentions that the legacy Three.js renderer code contains APIs incompatible with modern Three.js.

### Screenshots

1. `_1.png` — Betaflight App 2026.6.2, empty Setup model and DevTools console error.
2. `_2.png` — legacy 3D rendering option tested.
3. `_3.png` — standalone Betaflight Configurator 10.10.0 rendering the same model correctly.

<img width="1280" height="735" alt="Image" src="https://github.com/user-attachments/assets/fdef8afb-3f68-41e6-b353-77a14d22595c" />
<img width="882" height="605" alt="Image" src="https://github.com/user-attachments/assets/8a1b264f-da83-48c6-b780-7d2732381f4d" />
<img width="1276" height="736" alt="Image" src="https://github.com/user-attachments/assets/0f34409a-e846-4b34-9ca9-061c46a21150" />
