### ISSUE TITLE
Track incremental TypeScript migration

### ISSUE THREAD

**Issue by haslinghuis** [betaflight/betaflight-configurator#5141]
## Overview

Tracking issue for the next phase of the configurator migration: incremental TypeScript adoption. Picks up where the Vue/Pinia tab migration (#4812) lands and runs in parallel with the Nuxt UI v4 conversion (#4995) and Pinia single-source-of-truth work (#4800).

Standards for new TS code are documented in [`AGENTS.md`](https://github.com/betaflight/betaflight-configurator/blob/master/AGENTS.md) (added in #5140).

## Motivation

- Type safety on MSP encode/decode reduces a class of silent protocol bugs.
- Typed Pinia stores make the legacy `FC` singleton retirement (#4800) compiler-enforced rather than reviewer-enforced.
- Cross-domain refactors (store extractions, composables) get safer.
- Sets up future contributions to use TS by default.

## Phase plan

Three sequential phases, each enabling tooling that makes the next one's invariants checkable.

### Phase 0 — Enforcement tooling prep (no TS yet)

Land the lint/Stylelint/hook tooling that AGENTS.md references. New code only — existing violations grandfathered, each allowlist shrinks as Phase 1 / 2 progresses.

| PR | Rule | Grandfather size | Notes |
|---|---|---|---|
| 0.1 | `.vue` filenames PascalCase (`eslint-plugin-unicorn/filename-case`) | **0 files** | Apply tree-wide, no allowlist — instant signal |
| 0.2 | Pre-commit: reject non-`en` locale edits | **0** | Husky extension; Crowdin sync uses `--no-verify` |
| 0.3 | Pre-commit: reject `dist/` / `src/dist/` / `node_modules/` commits | **0** | Husky extension; may bundle with 0.2 |
| 0.4 | ESLint `no-restricted-imports`: ban `src/js/msp/**` from `src/components/**` | **20 files** (16 `.vue` + 4 `.js`) | Concrete allowlist baked in; shrinks per #4800 |
| 0.5 | Stylelint: forbid hex color literals (`color-no-hex`) | **~24 files** | Heaviest change (new tooling); shrinks per #4995 |

- [ ] 0.1 — Vue filename PascalCase
- [ ] 0.2 — Locale pre-commit hook
- [ ] 0.3 — Generated-paths pre-commit hook
- [ ] 0.4 — MSP-from-components boundary
- [ ] 0.5 — Stylelint hex colors

### Phase 1 — Per-domain JSDoc + boundary lint

Bundled with each TS / Nuxt UI conversion PR for that domain:

- [ ] JSDoc types on touched legacy `.js` files during migration
- [ ] `eslint-plugin-boundaries` scoped per domain: only `src/stores/**` and `src/composables/**` may import `src/js/msp/**`
- [ ] CI script diffing `src/js/msp/MSPCodes.js` against firmware `msp_protocol.h`
- [ ] Custom `eslint-plugin-vue` rule: no new `<style scoped>` blocks in converted tabs

### Phase 2 — Full TS conversion

Target files in dependency order (low-risk leaves first):

- [ ] `tsconfig.json` baseline (`allowJs: true`, `checkJs: false`, strict per-folder via overrides)
- [ ] `src/stores/**` → `.ts` (typed state, getters, actions)
- [ ] `src/composables/**` → `.ts`
- [ ] `src/js/msp/MSPCodes.js` → `.ts` (typed enum)
- [ ] `src/js/msp/MSPHelper.js` → `.ts` (typed encode/decode)
- [ ] `src/js/fc.js` → `src/stores/fc.ts` (sealed interface; closes the "no new fields on FC" row in AGENTS.md)
- [ ] `src/components/**` → `<script setup lang="ts">` (per-tab, in lockstep with #4995 conversions)
- [ ] Flip `allowJs: false` on `src/components/**`
- [ ] Ratchet `"strict": true` per folder

## Standards for new TS code

See [`AGENTS.md` § TypeScript integration](https://github.com/betaflight/betaflight-configurator/blob/master/AGENTS.md). Highlights:

- New files: `.ts` or `<script setup lang="ts">` with `defineProps` / `defineEmits`
- `PropType<T>` for typed props and default values
- Interfaces or type aliases for complex prop and state shapes
- Type event handlers, refs, store getters and actions explicitly

## Migration rules

Carried over from #4812 conventions:

- One file/domain per PR
- Feature parity first — migrate without adding features or new error handling
- Tests stay green throughout (Vitest)
- Phase 0 grandfather allowlists shrink as files are converted

## Acceptance criteria

- `allowJs: false` enabled across `src/stores/`, `src/composables/`, `src/components/`, and `src/js/msp/`
- `strict: true` enabled in the same scope
- Legacy `FC` singleton removed; Pinia stores are typed SSoT (#4800)
- Phase 0 grandfather allowlists are empty — corresponding AGENTS.md rows can be deleted
- Documentation updated (this issue, AGENTS.md, contributor docs)

## Related

- #4800 — Pinia SSoT (Phase 1/2 enables much of this)
- #4812 — Vue/Pinia tab migration (essentially complete; this picks up after)
- #4995 — Nuxt UI v4 conversion (parallel; Phase 2 component TS conversions bundle with Nuxt UI work)
- #4865 — original AGENTS.md RFC
- #5140 — AGENTS.md introduced

**Comment by blckmn** [comment]
Opened #5542 with a prioritised per-file conversion order, as a companion to the Phase 2 list here. Ordering is highest fan-in leaves first, with the FC/stores work left sitting behind #4800 per the sequencing note above.

**Comment by haslinghuis** [comment]
Something surfaced while converting `bit.js` (#5561) that bears on the phasing here rather than on that PR.

**No `.vue` file in the repo is typechecked.** Not one of the 136 uses `lang="ts"`, so `vue-tsc` treats every script block as JavaScript and `checkJs: false` skips it.

```
$ grep -rl '<script[^>]*lang="ts"' src --include=*.vue | wc -l
0
$ find src -name "*.vue" -not -path "src/dist/*" | wc -l
136
```

Direct demonstration — this identical line is silently **accepted** in `BottomStatusIcons.vue` and **rejected** in a `.ts` file:

```js
const deliberate = bit_check("not a number", "also not");
```

**Why it matters for the ordering.** #5542 sequences by "highest fan-in leaves first, so each PR types the most callers for the least risk". That holds only if the callers are checked. Today none of the three caller kinds is, except `.ts`:

| Caller | Checked? |
| --- | --- |
| `.js` | no — `checkJs: false` |
| `.vue` | no — no `lang="ts"` anywhere |
| `.ts` / `.test.ts` | yes |

Measured on `bit.js`: inverting its signature to `(string, string)` and typechecking the tree produces errors in `bit.ts` and **nowhere else** — 0 of 20 importers. The same measurement is worth running on any leaf before claiming a conversion "puts types under N callers"; `gui_log` and `ConfigStorage` will have a better ratio than `bit` because more of their importers are already `.ts`, but the `.vue` share is dead weight in every case.

This does not make the leaf conversions wrong — the types land, and they start biting as importers convert, which is the direction the list is going anyway. But the payoff is deferred rather than immediate, and the fan-in numbers overstate the near-term benefit.

**Worth considering:** adding `lang="ts"` to a `.vue` file is close to free where the script block is already valid TypeScript (no annotations required — it just stops being skipped). If that is true for a decent share of the 136, a cheap early pass over the `.vue` files that import already-converted leaves would turn the existing conversions into real checking, rather than waiting for each importer's own conversion. I have not measured how many would compile clean; happy to if it is useful.

Related: this is the same class as #5554, where `test/**/*.ts` was missing from the tsconfig `include` and the five `.test.ts` files were renames with nothing behind them. Turning that on surfaced 55 real errors.

**Comment by haslinghuis** [comment]
Measured it, and opened #5562 with the free part.

**Enabling `lang="ts"` on all 136 gives 4014 errors — but 30 files come back completely clean.**

| Errors in file | Files |
| --- | --- |
| **0 — free** | **30** |
| 1–2 | 24 |
| 3–5 | 18 |
| 6–20 | 20 |
| >20 | 44 |

| Code | Count | What it is |
| --- | --- | --- |
| TS2339 | 1105 | property does not exist on type |
| TS7006 | 969 | parameter implicitly `any` |
| TS18047 | 712 | value possibly `null` |
| TS7005 / TS7034 | 447 | variable implicitly `any` |
| TS2322 | 236 | type not assignable |
| TS2554 | 149 | wrong number of arguments |
| TS7053 | 105 | implicit `any` from index expression |

Roughly half is implicit-`any` noise that `noImplicitAny` would want annotated. The 712 possibly-`null` dereferences and 149 wrong-arity calls are the ones likely hiding real bugs.

Enabling `.vue` checking produced **no** new errors in any `.ts` file, so it does not cascade — this can be done incrementally, file by file, with no big-bang step.

#5562 turns on the 30 clean ones. That is a one-word change per file, and I checked it is not cosmetic: `Math.round("definitely not a number")` is now rejected in `BottomStatusIcons.vue` and still silently accepted in `SensorsTab.vue`, which is not in the set.

**Suggested sequencing, if you want the rest:** the 24 files at 1–2 errors are the natural next slice and should be a couple of small PRs. The 44 at >20 are not worth doing as typing work on their own — they are mostly the big tabs, and most of their errors come from reading the `FC` singleton, so they will get much cheaper after #4800 reshapes it. I would leave those until then rather than annotate around a shape that is about to change.

One consequence for #5542's ordering worth recording: "highest fan-in leaves first, so each PR types the most callers" is measuring importers, not *checked* importers. On `bit.js` (#5561) that was 0 of 20. The leaf conversions are still right — the types land and start biting as importers convert — but the payoff is deferred, and `.vue` importers contribute nothing until they are switched on. Turning on the cheap `.vue` files early is what makes the already-converted leaves actually pay.
